### ISSUE TITLE
Вообще на Stack не очень похоже. Скорее вы vector патались повторить

### ISSUE THREAD

**Issue by ahvastunov-itmo** [Fellzo/JsonParser#5]
https://github.com/Fellzo/JsonParser/blob/e2e6e658fb8d34a9ec7ad3b22f0b08f97f1e745c/stack.h#L10

**Comment by Fellzo** [comment]
Ну по сути стек - вектор с поддержкой операций добавить в конец, вытащить из конца проверить на пустоту?
