### ISSUE TITLE
Где мы ее удаляем? 

### ISSUE THREAD

**Issue by ahvastunov-itmo** [Fellzo/JsonParser#8]
https://github.com/Fellzo/JsonParser/blob/c254f27ca8cdd51ee6ed72452468659828091d7b/main.c#L35

**Comment by Fellzo** [comment]
В моем представление - корневая вершина живет до конца работы программы

**Comment by ahvastunov-itmo** [comment]
Это не означает что стоит расчитывать на то что операционная система пометит эту память как свободнаю. Требуется явно чистить и взять это за правило

**Comment by Fellzo** [comment]
Понял, исравлено
